Salon/Models/Client.cs
namespace Salon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string ClientName { get; set; }
    public int StylistsId { get; set; }
    public virtual Stylist Stylist { get; set; }

  }
}

Salon/Models/SalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace Salon.Models
{
  public class SalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public SalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Salon/Models/Stylists.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Salon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }
    [Key]
    public int StylistsId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

Salon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using System.Collections.Generic;
using System.Linq;

namespace Salon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly SalonContext _db;

    public ClientsController(SalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistsId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistsId = new SelectList(_db.Stylists, "StylistsId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Salon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Salon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

Salon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using System.Collections.Generic;
using System.Linq;

namespace Salon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly SalonContext _db;

    public StylistsController(SalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistsId == id);
      return View(thisStylist);
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistsId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistsId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistsId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Salon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h4>Add a new Client</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.ClientName)
  @Html.TextBoxFor(model => model.ClientName)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("ClientId")

  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

Salon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Salon/Views/Clients/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/items">Back to list.</a></p>

Salon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>

Salon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.ClientName)
  @Html.EditorFor(model => model.ClientName)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("ClientId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Salon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model List<Salon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.ClientName}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p>@Html.ActionLink("Add new client", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Salon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Eau Claire's Salon!</h1>
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p> <p>@Html.ActionLink("See all clients", "Index", "Clients")</p>

Salon/Views/Shared/Footer.cshtml
<div id="footer">Eau Claire's Salon!</div>

Salon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>

Salon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

Salon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Are you sure you want to delete this stylist?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Salon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Category Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistsId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistsId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Salon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistsId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Salon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistsId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>